Mimic.copy(AshAuthentication.Plug.Defaults)
Mimic.copy(AshAuthentication.Plug.Helpers)
Mimic.copy(AshAuthentication.Strategy.Confirmation.Actions)
Mimic.copy(AshAuthentication.Strategy.Confirmation.Plug)
Mimic.copy(AshAuthentication.Strategy.OAuth2.Actions)
Mimic.copy(AshAuthentication.Strategy.OAuth2.Plug)
Mimic.copy(AshAuthentication.Strategy.Password.Actions)
Mimic.copy(AshAuthentication.Strategy.Password.Plug)
Mimic.copy(AshAuthentication.TokenRevocation)
ExUnit.start(capture_log: true)
