version: "3.8"

volumes:
  apt-cache: {}
  history: {}
  db-data: {}
  app-asdf: {}
  app-elixir-ls: {}
  app-storage: {}
  ash-authentication-deps: {}
  ash-authentication-build: {}
  ash-auth-example-deps: {}
  ash-auth-example-build: {}

services:
  app:
    environment:
      LOGGER_LEVEL: 1
      PGHOST: db
      PGPORT: 5432
      PGUSER: postgres
      PGDATABASE: app
      HISTFILE: /var/tmp/history/shell.history
      GIT_AUTHOR_EMAIL:
      GIT_COMMITTER_EMAIL:
      GITHUB_TOKEN:
      PORT: 400
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
      args:
        HEX_API_KEY:
        GITHUB_TOKEN:

    volumes:
      - ..:/workspace:cached
      - "apt-cache:/var/cache/apt:rw"
      - "history:/var/tmp/history:rw"
      - "app-asdf:/home/vscode/.asdf:rw"
      - "app-elixir-ls:/workspace/.elixir_ls:rw"
      - "app-storage:/storage:rw"
      - "ash-authentication-deps:/workspace/ash_authentication/deps:rw"
      - "ash-authentication-build:/workspace/ash_authentication/_build:rw"
      - "ash-auth-example-deps:/workspace/ash_auth_example/deps:rw"
      - "ash-auth-example-build:/workspace/ash_auth_example/_build:rw"
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
