defmodule Example.Repo.Migrations.AddConfirmedAtToUserWuthUsername do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:user_with_username) do
      add :confirmed_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:user_with_username) do
      remove :confirmed_at
    end
  end
end