defmodule Example.Repo.Migrations.AddTokenRevocationTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:user_with_username, [:username],
             name: "user_with_username_username_index"
           )

    create table(:token_revocations, primary_key: false) do
      add :expires_at, :utc_datetime, null: false
      add :jti, :text, null: false, primary_key: true
    end
  end

  def down do
    drop table(:token_revocations)

    drop_if_exists unique_index(:user_with_username, [:username],
                     name: "user_with_username_username_index"
                   )
  end
end