defmodule Example.Repo.Migrations.RenameCreatedAtToInsertedAt do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:user_with_token_required), :created_at, to: :inserted_at

    rename table(:user), :created_at, to: :inserted_at

    rename table(:tokens), :created_at, to: :inserted_at
  end

  def down do
    rename table(:tokens), :inserted_at, to: :created_at

    rename table(:user), :inserted_at, to: :created_at

    rename table(:user_with_token_required), :inserted_at, to: :created_at
  end
end