# SPDX-FileCopyrightText: 2022 Alembic Pty Ltd
#
# SPDX-License-Identifier: MIT

defmodule Example.Repo.Migrations.AddTotpExamples do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:audit_logged_users) do
      add(:totp_secret, :text)
      add(:last_totp_at, :utc_datetime)
    end
  end

  def down do
    alter table(:audit_logged_users) do
      remove(:last_totp_at)
      remove(:totp_secret)
    end
  end
end
