# SPDX-FileCopyrightText: 2025 Alembic Pty Ltd
#
# SPDX-License-Identifier: MIT

defmodule Example.Repo.Migrations.FixTotpSecretType do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("ALTER TABLE audit_logged_users ALTER COLUMN totp_secret TYPE bytea USING totp_secret::bytea")
  end

  def down do
    alter table(:audit_logged_users) do
      modify(:totp_secret, :text)
    end
  end
end
