# SPDX-FileCopyrightText: 2022 Alembic Pty Ltd
#
# SPDX-License-Identifier: MIT

defmodule Example.Repo.Migrations.AddTotpConfirmSetupUsers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:totp_confirm_setup_users, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:email, :citext, null: false)
      add(:hashed_password, :text)
      add(:totp_secret, :binary)
      add(:last_totp_at, :utc_datetime)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create unique_index(:totp_confirm_setup_users, [:email],
             name: "totp_confirm_setup_users_unique_email_index"
           )
  end

  def down do
    drop_if_exists(
      unique_index(:totp_confirm_setup_users, [:email],
        name: "totp_confirm_setup_users_unique_email_index"
      )
    )

    drop(table(:totp_confirm_setup_users))
  end
end
