defmodule Example.Repo.Migrations.CreateMigrationsForNewResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users_with_excluded_strategies, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:email, :citext, null: false)
      add(:hashed_password, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create unique_index(:users_with_excluded_strategies, [:email],
             name: "users_with_excluded_strategies_unique_email_index"
           )

    create table(:users_with_excluded_actions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:email, :citext, null: false)
      add(:hashed_password, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create unique_index(:users_with_excluded_actions, [:email],
             name: "users_with_excluded_actions_unique_email_index"
           )
  end

  def down do
    drop_if_exists(
      unique_index(:users_with_excluded_actions, [:email],
        name: "users_with_excluded_actions_unique_email_index"
      )
    )

    drop(table(:users_with_excluded_actions))

    drop_if_exists(
      unique_index(:users_with_excluded_strategies, [:email],
        name: "users_with_excluded_strategies_unique_email_index"
      )
    )

    drop(table(:users_with_excluded_strategies))
  end
end
