defmodule Example.Repo.Migrations.AddAuditLogFieldToAuditLogs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename(table(:audit_logs), :event_name, to: :action_name)

    alter table(:audit_logs) do
      modify(:subject, :text, null: true)
      add(:audit_log, :text, null: false)
    end
  end

  def down do
    alter table(:audit_logs) do
      remove(:audit_log)
      modify(:subject, :text, null: false)
    end

    rename(table(:audit_logs), :action_name, to: :event_name)
  end
end
