defmodule Example.Repo.Migrations.AddTotpDetails do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:user) do
      add(:totp_details, :map)
    end
  end

  def down do
    alter table(:user) do
      remove(:totp_details)
    end
  end
end
