# SPDX-FileCopyrightText: 2022 Alembic Pty Ltd
#
# SPDX-License-Identifier: MIT

defmodule Example.Repo.Migrations.AddConfirmationCheckTestResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:user_with_confirmation_field_policy, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:email, :citext, null: false)
      add(:hashed_password, :text)
      add(:confirmed_at, :utc_datetime_usec)
    end

    create unique_index(:user_with_confirmation_field_policy, [:email],
             name: "user_with_confirmation_field_policy_email_index"
           )

    create table(:user_with_required_confirmation, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:email, :citext, null: false)
      add(:hashed_password, :text)
      add(:confirmed_at, :utc_datetime_usec)
    end

    create unique_index(:user_with_required_confirmation, [:email],
             name: "user_with_required_confirmation_email_index"
           )

    create table(:user_with_unselected_confirmation, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:email, :citext, null: false)
      add(:hashed_password, :text)
      add(:confirmed_at, :utc_datetime_usec)
    end

    create unique_index(:user_with_unselected_confirmation, [:email],
             name: "user_with_unselected_confirmation_email_index"
           )
  end

  def down do
    drop_if_exists(
      unique_index(:user_with_unselected_confirmation, [:email],
        name: "user_with_unselected_confirmation_email_index"
      )
    )

    drop(table(:user_with_unselected_confirmation))

    drop_if_exists(
      unique_index(:user_with_required_confirmation, [:email],
        name: "user_with_required_confirmation_email_index"
      )
    )

    drop(table(:user_with_required_confirmation))

    drop_if_exists(
      unique_index(:user_with_confirmation_field_policy, [:email],
        name: "user_with_confirmation_field_policy_email_index"
      )
    )

    drop(table(:user_with_confirmation_field_policy))
  end
end
