# SPDX-FileCopyrightText: 2022 Alembic Pty Ltd
#
# SPDX-License-Identifier: MIT

defmodule Example.Repo.Migrations.AddAuditLogIdentityAndClientIp do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:audit_logs_no_expiry) do
      add(:client_ip, :text)
      add(:identity, :text)
    end

    alter table(:audit_logs) do
      add(:client_ip, :text)
      add(:identity, :text)
    end
  end

  def down do
    alter table(:audit_logs) do
      remove(:identity)
      remove(:client_ip)
    end

    alter table(:audit_logs_no_expiry) do
      remove(:identity)
      remove(:client_ip)
    end
  end
end
