# SPDX-FileCopyrightText: 2022 Alembic Pty Ltd
#
# SPDX-License-Identifier: MIT

defmodule Example.Repo.Migrations.MultitenantUserIdentity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists(
      unique_index(:mt_user_identities, [:strategy, :uid],
        name: "mt_user_identities_unique_on_strategy_and_uid_index"
      )
    )

    create unique_index(:mt_user_identities, [:organisation_id, :strategy, :uid],
             name: "mt_user_identities_unique_on_strategy_and_uid_index"
           )
  end

  def down do
    drop_if_exists(
      unique_index(:mt_user_identities, [:organisation_id, :strategy, :uid],
        name: "mt_user_identities_unique_on_strategy_and_uid_index"
      )
    )

    create unique_index(:mt_user_identities, [:strategy, :uid],
             name: "mt_user_identities_unique_on_strategy_and_uid_index"
           )
  end
end
