# SPDX-FileCopyrightText: 2026 Alembic Pty Ltd
#
# SPDX-License-Identifier: MIT

defmodule Example.Repo.Migrations.AddCustomRegisterFieldTestAttributes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:user) do
      add(:personal_number, :text)
    end

    alter table(:user_with_webauthn) do
      add(:name, :text)
      add(:personal_number, :text)
    end
  end

  def down do
    alter table(:user_with_webauthn) do
      remove(:personal_number)
      remove(:name)
    end

    alter table(:user) do
      remove(:personal_number)
    end
  end
end
