defmodule Example.Repo.Migrations.MigrateResources3 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:user) do
      remove(:personal_number)
    end

    alter table(:webauthn_credentials) do
      add(:user_handle, :binary)
    end

    alter table(:webauthn_no_identity_credentials) do
      add(:user_handle, :binary)
    end
  end

  def down do
    alter table(:webauthn_no_identity_credentials) do
      remove(:user_handle)
    end

    alter table(:webauthn_credentials) do
      remove(:user_handle)
    end

    alter table(:user) do
      add(:personal_number, :text)
    end
  end
end
