defmodule Example.Repo.Migrations.MigrateResources4 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:webauthn_credentials) do
      add(:backed_up, :boolean)
      add(:backup_eligible, :boolean)
      add(:transports, {:array, :text})
    end

    alter table(:webauthn_no_identity_credentials) do
      add(:backed_up, :boolean)
      add(:backup_eligible, :boolean)
      add(:transports, {:array, :text})
    end
  end

  def down do
    alter table(:webauthn_no_identity_credentials) do
      remove(:transports)
      remove(:backup_eligible)
      remove(:backed_up)
    end

    alter table(:webauthn_credentials) do
      remove(:transports)
      remove(:backup_eligible)
      remove(:backed_up)
    end
  end
end
