defmodule Example.Repo.Migrations.RequireUserIdentityUniqueKey do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists(
      unique_index(:user_identities, [:strategy, :uid, :user_id],
        name: "user_identities_unique_on_strategy_and_uid_and_user_id_index"
      )
    )

    create unique_index(:user_identities, [:strategy, :uid],
             name: "user_identities_unique_on_strategy_and_uid_index"
           )

    drop_if_exists(
      unique_index(:mt_user_identities, [:strategy, :uid, :user_id],
        name: "mt_user_identities_unique_on_strategy_and_uid_and_user_id_index"
      )
    )

    create unique_index(:mt_user_identities, [:strategy, :uid],
             name: "mt_user_identities_unique_on_strategy_and_uid_index"
           )
  end

  def down do
    drop_if_exists(
      unique_index(:mt_user_identities, [:strategy, :uid],
        name: "mt_user_identities_unique_on_strategy_and_uid_index"
      )
    )

    create unique_index(:mt_user_identities, [:strategy, :uid, :user_id],
             name: "mt_user_identities_unique_on_strategy_and_uid_and_user_id_index"
           )

    drop_if_exists(
      unique_index(:user_identities, [:strategy, :uid],
        name: "user_identities_unique_on_strategy_and_uid_index"
      )
    )

    create unique_index(:user_identities, [:strategy, :uid, :user_id],
             name: "user_identities_unique_on_strategy_and_uid_and_user_id_index"
           )
  end
end
