# SPDX-FileCopyrightText: 2022 Alembic Pty Ltd
#
# SPDX-License-Identifier: MIT

defmodule Example.Repo.Migrations.AddUserWithOauth2Email do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:oauth2_email_user_identities, primary_key: false) do
      add(:refresh_token, :text)
      add(:access_token_expires_at, :utc_datetime_usec)
      add(:access_token, :text)
      add(:uid, :text, null: false)
      add(:strategy, :text, null: false)
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:user_id, :uuid)
    end

    create unique_index(:oauth2_email_user_identities, [:strategy, :uid],
             name: "oauth2_email_user_identities_unique_on_strategy_and_uid_index"
           )

    create table(:user_with_oauth2_email, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:oauth2_email_user_identities) do
      modify(
        :user_id,
        references(:user_with_oauth2_email,
          column: :id,
          name: "oauth2_email_user_identities_user_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:user_with_oauth2_email) do
      add(:email, :citext)
      add(:username, :citext)

      add(:created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create unique_index(:user_with_oauth2_email, [:email],
             name: "user_with_oauth2_email_unique_email_index"
           )

    create unique_index(:user_with_oauth2_email, [:username],
             name: "user_with_oauth2_email_unique_username_index"
           )
  end

  def down do
    drop_if_exists(
      unique_index(:user_with_oauth2_email, [:username],
        name: "user_with_oauth2_email_unique_username_index"
      )
    )

    drop_if_exists(
      unique_index(:user_with_oauth2_email, [:email],
        name: "user_with_oauth2_email_unique_email_index"
      )
    )

    alter table(:user_with_oauth2_email) do
      remove(:updated_at)
      remove(:created_at)
      remove(:username)
      remove(:email)
    end

    drop(constraint(:oauth2_email_user_identities, "oauth2_email_user_identities_user_id_fkey"))

    alter table(:oauth2_email_user_identities) do
      modify(:user_id, :uuid)
    end

    drop(table(:user_with_oauth2_email))

    drop_if_exists(
      unique_index(:oauth2_email_user_identities, [:strategy, :uid],
        name: "oauth2_email_user_identities_unique_on_strategy_and_uid_index"
      )
    )

    drop(table(:oauth2_email_user_identities))
  end
end
