# SPDX-FileCopyrightText: 2026 Alembic Pty Ltd
#
# SPDX-License-Identifier: MIT

defmodule Example.Repo.Migrations.AddUnstoredWebauthnResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:user_with_unstored_webauthn, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:email, :citext, null: false)

      add(:created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create unique_index(:user_with_unstored_webauthn, [:email],
             name: "user_with_unstored_webauthn_unique_email_index"
           )

    create table(:unstored_webauthn_credentials, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:credential_id, :binary, null: false)
      add(:public_key, :binary, null: false)
      add(:sign_count, :bigint, null: false, default: 0)
      add(:label, :text, default: "Security Key")
      add(:last_used_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :user_id,
        references(:user_with_unstored_webauthn,
          column: :id,
          name: "unstored_webauthn_credentials_user_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end

    create unique_index(:unstored_webauthn_credentials, [:credential_id],
             name: "unstored_webauthn_credentials_unique_credential_id_index"
           )
  end

  def down do
    drop(constraint(:unstored_webauthn_credentials, "unstored_webauthn_credentials_user_id_fkey"))

    drop_if_exists(
      unique_index(:unstored_webauthn_credentials, [:credential_id],
        name: "unstored_webauthn_credentials_unique_credential_id_index"
      )
    )

    drop(table(:unstored_webauthn_credentials))

    drop_if_exists(
      unique_index(:user_with_unstored_webauthn, [:email],
        name: "user_with_unstored_webauthn_unique_email_index"
      )
    )

    drop(table(:user_with_unstored_webauthn))
  end
end
