# SPDX-FileCopyrightText: 2026 Alembic Pty Ltd
#
# SPDX-License-Identifier: MIT

defmodule Example.Repo.Migrations.AddWebauthnSpecFieldsToUnstoredCredentials do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:unstored_webauthn_credentials) do
      add(:discoverable, :boolean)
      add(:backed_up, :boolean)
      add(:backup_eligible, :boolean)
      add(:transports, {:array, :text})
      add(:user_handle, :binary)
    end
  end

  def down do
    alter table(:unstored_webauthn_credentials) do
      remove(:user_handle)
      remove(:transports)
      remove(:backup_eligible)
      remove(:backed_up)
      remove(:discoverable)
    end
  end
end
