defmodule Example.Repo.Migrations.AddWebauthn do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:webauthn_credentials, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:credential_id, :binary, null: false)
      add(:public_key, :binary, null: false)
      add(:sign_count, :bigint, null: false, default: 0)
      add(:label, :text, default: "Security Key")
      add(:last_used_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:user_id, :uuid, null: false)
    end

    create table(:user_with_webauthn, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:webauthn_credentials) do
      modify(
        :user_id,
        references(:user_with_webauthn,
          column: :id,
          name: "webauthn_credentials_user_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    create unique_index(:webauthn_credentials, [:credential_id],
             name: "webauthn_credentials_unique_credential_id_index"
           )

    alter table(:user_with_webauthn) do
      add(:email, :citext, null: false)

      add(:created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create unique_index(:user_with_webauthn, [:email],
             name: "user_with_webauthn_unique_email_webauthn_index"
           )
  end

  def down do
    drop_if_exists(
      unique_index(:user_with_webauthn, [:email],
        name: "user_with_webauthn_unique_email_webauthn_index"
      )
    )

    alter table(:user_with_webauthn) do
      remove(:updated_at)
      remove(:created_at)
      remove(:email)
    end

    drop_if_exists(
      unique_index(:webauthn_credentials, [:credential_id],
        name: "webauthn_credentials_unique_credential_id_index"
      )
    )

    drop(constraint(:webauthn_credentials, "webauthn_credentials_user_id_fkey"))

    alter table(:webauthn_credentials) do
      modify(:user_id, :uuid)
    end

    drop(table(:user_with_webauthn))

    drop(table(:webauthn_credentials))
  end
end
