defmodule Example.Repo.Migrations.MigrateResources5 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:webauthn_credentials) do
      add(:discoverable, :boolean)
    end

    alter table(:webauthn_no_identity_credentials) do
      add(:discoverable, :boolean)
    end
  end

  def down do
    alter table(:webauthn_no_identity_credentials) do
      remove(:discoverable)
    end

    alter table(:webauthn_credentials) do
      remove(:discoverable)
    end
  end
end
