# SPDX-FileCopyrightText: 2026 Alembic Pty Ltd
#
# SPDX-License-Identifier: MIT

defmodule Example.Repo.Migrations.AddWebauthnWithoutIdentityExample do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:user_with_webauthn_no_identity, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)

      add(:created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:webauthn_no_identity_credentials, primary_key: false) do
      add(:last_used_at, :utc_datetime_usec)
      add(:label, :text, default: "Security Key")
      add(:sign_count, :bigint, null: false, default: 0)
      add(:public_key, :binary, null: false)
      add(:credential_id, :binary, null: false)
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :user_id,
        references(:user_with_webauthn_no_identity,
          column: :id,
          name: "webauthn_no_identity_credentials_user_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end

    create unique_index(:webauthn_no_identity_credentials, [:credential_id],
             name: "webauthn_no_identity_credentials_unique_credential_id_index"
           )
  end

  def down do
    drop(
      constraint(
        :webauthn_no_identity_credentials,
        "webauthn_no_identity_credentials_user_id_fkey"
      )
    )

    drop_if_exists(
      unique_index(:webauthn_no_identity_credentials, [:credential_id],
        name: "webauthn_no_identity_credentials_unique_credential_id_index"
      )
    )

    drop(table(:webauthn_no_identity_credentials))

    drop(table(:user_with_webauthn_no_identity))
  end
end
