# SPDX-FileCopyrightText: 2022 Alembic Pty Ltd
#
# SPDX-License-Identifier: MIT

defmodule Example.Repo.Migrations.AddRecoveryCodes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:recovery_codes, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:code, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:user_id, :uuid, null: false)
    end

    create table(:recovery_code_users, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:recovery_codes) do
      modify(
        :user_id,
        references(:recovery_code_users,
          column: :id,
          name: "recovery_codes_user_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all
        )
      )
    end

    alter table(:recovery_code_users) do
      add(:email, :citext, null: false)
      add(:hashed_password, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create unique_index(:recovery_code_users, [:email],
             name: "recovery_code_users_unique_email_index"
           )
  end

  def down do
    drop_if_exists(
      unique_index(:recovery_code_users, [:email], name: "recovery_code_users_unique_email_index")
    )

    alter table(:recovery_code_users) do
      remove(:updated_at)
      remove(:inserted_at)
      remove(:hashed_password)
      remove(:email)
    end

    drop(constraint(:recovery_codes, "recovery_codes_user_id_fkey"))

    alter table(:recovery_codes) do
      modify(:user_id, :uuid)
    end

    drop(table(:recovery_code_users))

    drop(table(:recovery_codes))
  end
end
