# SPDX-FileCopyrightText: 2022 Alembic Pty Ltd
#
# SPDX-License-Identifier: MIT

defmodule Example.Repo.Migrations.AddAuditLogNoExpiry do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:audit_logs_no_expiry, primary_key: false) do
      add(:resource, :text, null: false)
      add(:extra_data, :map, null: false, default: %{})
      add(:status, :text, null: false)
      add(:action_name, :text, null: false)

      add(:logged_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:audit_log, :text, null: false)
      add(:strategy, :text, null: false)
      add(:subject, :text)
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
    end
  end

  def down do
    drop(table(:audit_logs_no_expiry))
  end
end
